apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      argocd.argoproj.io/sync-options: Prune=true
    name: nstest
    namespace: argocd
  spec:
    syncPolicy:
      automated:
        prune: true
    destination:
      namespace: test
      server: https://kubernetes.default.svc
    project: default
    source:
      repoURL: https://github.com/deepakal/public.git
      targetRevision: HEAD
      path: ns1
      directory:
        exclude: '{*.json}'
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
