apiVersion: cnf.nokia.com/v1alpha1
kind: ZTS
metadata:
  annotations:
    crossplane.io/claim-namespace: nc-system
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    crossplane.io/claim-name: test
  name: myclaim
  namespace: nc-system
spec:
  compositionRef:
    name: zts-service
  compositionUpdatePolicy: Automatic
  providerConfigRef:
    name: providerconfig
  parameters:
    profileOperator:
      releaseName: profile-operator
      chartName: ncm-app
      chartVersion: 1.15.20
      repository: https://repo.cci.nokia.net/artifactory/csf-helm-stable/
      namespace: cnf
    helmrepo:
      releaseName: custom-helmrepo
      chartName: helmrepo
      chartVersion: 1.0.3
      repository:  https://repo.cci.nokia.net/artifactory/csf-helm-stable/
      namespace: cnf
      valueFrom:
        key: value.yaml
        name: helmrepo
    ztsService:
      releaseName: zts-services
      chartName: zts-services
      chartVersion: 4.0.0
      repository: http://10.92.133.68/charts/
      namespace: cnf

  resourceCompositionName: zts
