apiVersion: cnf.nokia.com/v1alpha1
kind: ZTS
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: myclaim
  namespace: nc-system
spec:
  compositionRef:
    name: zts-service
  compositionUpdatePolicy: Automatic
  providerConfigRef:
    name: providerconfig
  parameters:
    profileOperator:
      releaseName: profile-operator
      chartName: ncm-app
      chartVersion: 1.15.20
      repository: https://repo.cci.nokia.net/artifactory/csf-helm-stable/
      namespace: cnf
      values:
        autonomous:
          enabled: true
        webhook:
          validate: false
        controller: true
        helm3Only: true
        checkLabelling: false
        namespaced:
          enabled: true    
        nodeSelector: ""
        tolerations: ""
    helmrepo:
      releaseName: custom-helmrepo
      chartName: helmrepo
      chartVersion: 1.0.3
      repository:  https://repo.cci.nokia.net/artifactory/csf-helm-stable/
      namespace: cnf
      valueFrom:
        key: value.yaml
        name: helmrepo
    ztsService:
      releaseName: zts-services
      chartName: zts-services
      chartVersion: 5.0.0
      repository: http://10.92.133.68/charts/
      namespace: cnf

  resourceCompositionName: zts
