apiVersion: apps/v1
kind: Deployment
metadata:
  name: ns1
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 90
        env:
        - name: HTTP_PROXY
          value: "http://10.158.100.1:8080/"
        - name: HTTPS_PROXY
          value: "http://10.158.100.1:8080/"          
