apiVersion: cnf.nokia.com/v1alpha1
kind: ZTS
metadata:
  annotations:
    crossplane.io/claim-namespace: upbound-system
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/compare-options: IgnoreExtraneous
  labels:
    crossplane.io/claim-name: test
  name: test
  namespace: upbound-system
spec:
  compositionRef:
    name: zts-service
  compositionUpdatePolicy: Automatic
  providerConfigRef:
    name: providerconfig
  parameters:
    profileOperator:
      releaseName: profile-operator
      chartName: ncm-app
      chartVersion: 1.15.20
      repository: https://repo.cci.nokia.net/artifactory/csf-helm-stable/
      namespace: upbound-system
      valueFrom:
        key: value.yaml
        name: profile
    helmrepo:
      releaseName: custom-helmrepo
      chartName: helmrepo
      chartVersion: 1.0.3
      repository:  https://repo.cci.nokia.net/artifactory/csf-helm-stable/
      namespace: upbound-system
      valueFrom:
        key: value.yaml
        name: helmrepo        
    ztsService:
      releaseName: zts-services
      chartName: zts-services
      repository: http://10.92.133.68/charts/
      namespace: upbound-system
      valueFrom:
        key: value.yaml
        name: zts
        
  resourceCompositionName: zts
